### ISSUE TITLE
No graphics are displayed

### ISSUE THREAD

**Issue by gxh1996** [pschraut/UnityDbgDraw#1]
Unity2020.3.13f1c1
Open the example and it can run without error, but no visual graphics are displayed。
![image](https://user-images.githubusercontent.com/48506232/147760311-8b13761f-b797-4126-9f33-12592c15b08b.png)

**Comment by gxh1996** [comment]
I see. To open `development build`

**Comment by pschraut** [comment]
Thank you for the bug-report. What render pipeline do you use? High-Definition Render Pipeline, Universal Render Pipeline or Built-in?

**Comment by gxh1996** [comment]
Built-in!This problem has been solved. Sorry, it's my problem. I didn't check development build in build settings.
