### ISSUE TITLE
Plane

### ISSUE THREAD

**Issue by luispedrofonseca** [pschraut/UnityDbgDraw#2]
First of all thanks for this great tool. It has helped me a lot to visualize a few things.

However, I was experimenting with the plane and it seems to be pointing in the incorrect direction -  a plane with the normal set to Vector3.forward is pointing towards the Y axis. I've also noticed that there's no demo for it. Can you please confirm if it's working as expected?

**Comment by pschraut** [comment]
Thank you for the bug-report. You're right, the implementation was wrong. It should be fixed in 1.1.0 which I just released. Please let me know whether it works for you now.

**Comment by luispedrofonseca** [comment]
Thanks, it seems to be working as expected now!
