### ISSUE TITLE
Library not working Unity 2022.3.2f1

### ISSUE THREAD

**Issue by slender9168** [pschraut/UnityDbgDraw#4]
Can't draw anything other than Shape.Text
I'm getting this error:

NullReferenceException: Object reference not set to an instance of an object
Vertx.Debugging.CommandBuilder.<FillCommandBuffer>g__RenderShape|65_1[T] (Vertx.Debugging.AssetsUtility+Asset`1[T] mesh, Vertx.Debugging.AssetsUtility+MaterialAsset material, Vertx.Debugging.CommandBuilder+ShapeBuffersWithData`1[T] shape, System.Int32 groupCount, Vertx.Debugging.CommandBuilder+<>c__DisplayClass65_0& , Vertx.Debugging.CommandBuilder+<>c__DisplayClass65_1& ) (at Assets/Vertx.Debugging-master/Runtime/CommandBuilder/CommandBuilder.cs:281)
Vertx.Debugging.CommandBuilder.<FillCommandBuffer>g__RenderShapes|65_0 (Vertx.Debugging.CommandBuilder+<>c__DisplayClass65_0& ) (at Assets/Vertx.Debugging-master/Runtime/CommandBuilder/CommandBuilder.cs:263)
Vertx.Debugging.CommandBuilder.FillCommandBuffer (UnityEngine.Rendering.CommandBuffer commandBuffer, UnityEngine.Camera camera, Vertx.Debugging.CommandBuilder+BufferGroup group, Vertx.Debugging.CommandBuilder+RenderingType renderingType) (at Assets/Vertx.Debugging-master/Runtime/CommandBuilder/CommandBuilder.cs:251)
Vertx.Debugging.CommandBuilder.SharedRenderingDetails (UnityEngine.Camera camera, Vertx.Debugging.CommandBuilder+BufferGroup group, UnityEngine.Rendering.CommandBuffer& commandBuffer, Vertx.Debugging.CommandBuilder+RenderingType renderingType) (at Assets/Vertx.Debugging-master/Runtime/CommandBuilder/CommandBuilder.cs:214)
Vertx.Debugging.CommandBuilder.ExecuteDrawRenderPass (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.CommandBuffer commandBuffer, UnityEngine.Camera camera) (at Assets/Vertx.Debugging-master/Runtime/CommandBuilder/CommandBuilder.cs:164)
Vertx.Debugging.VertxDebuggingRenderPass.Execute (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.RenderingData& renderingData) (at Assets/Vertx.Debugging-master/Runtime/Passes/VertxDebuggingPass.URP.cs:50)
UnityEngine.Rendering.Universal.ScriptableRenderer.ExecuteRenderPass (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.ScriptableRenderPass renderPass, UnityEngine.Rendering.Universal.RenderingData& renderingData) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/ScriptableRenderer.cs:1490)
UnityEngine.Rendering.Universal.ScriptableRenderer.ExecuteBlock (System.Int32 blockIndex, UnityEngine.Rendering.Universal.ScriptableRenderer+RenderBlocks& renderBlocks, UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.RenderingData& renderingData, System.Boolean submit) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/ScriptableRenderer.cs:1446)
UnityEngine.Rendering.Universal.ScriptableRenderer.Execute (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.RenderingData& renderingData) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/ScriptableRenderer.cs:1248)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.RenderSingleCamera (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.CameraData& cameraData, System.Boolean anyPostProcessingEnabled) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/UniversalRenderPipeline.cs:650)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.RenderSingleCameraInternal (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Camera camera) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/UniversalRenderPipeline.cs:534)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext renderContext, System.Collections.Generic.List`1[T] cameras) (at ./Library/PackageCache/com.unity.render-pipelines.universal@14.0.8/Runtime/UniversalRenderPipeline.cs:376)
UnityEngine.Rendering.RenderPipeline.InternalRender (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at <c2d036c16ca64e0eb93703a3b13e733a>:0)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipe, System.IntPtr loopPtr, UnityEngine.Object renderRequest, Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle safety) (at <c2d036c16ca64e0eb93703a3b13e733a>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by pschraut** [comment]
> Can't draw anything other than Shape.Text

`DbgDraw` does not have an API named `Shape.Text`. The error is not caused by `DbgDraw` according to the stacktrace. It's caused by whatever you have in `Assets/Vertx.Debugging-master/`.

**Comment by slender9168** [comment]
sorry, posted in the wrong git project.
Thanks for notifying me
