### ISSUE TITLE
Does it work in normal build?

### ISSUE THREAD

**Issue by FroggerHH** [pschraut/UnityDbgDraw#5]

**Comment by pschraut** [comment]
DbgDraw works in a build only, if you tick the `Development Build` checkbox in the Build Settings window (File > Build Settings).

**Comment by FroggerHH** [comment]
Can I somehow make it work without this checkbox?

**Comment by pschraut** [comment]
I wrote the code that it only works in development builds on purpose. If you want to use it in non-development builds, you would need to change the code.
