### ISSUE TITLE
Error on android build

### ISSUE THREAD

**Issue by orkuncinfer** [pschraut/UnityDbgDraw#6]
Getting this error whenever i call DbgDraw.WireDisc on an android build. probably will get the same error with other drawing methods.
Exception: NullReferenceException: Object reference not set to an instance of an object.

Oddworm.Framework.DbgDraw+DbgDrawBehaviour.AllocMeshJob (System.Single duration, System.Boolean depthTest, UnityEngine.Rendering.CullMode cullMode, System.Boolean shaded) (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw.TryAllocMeshJob (Oddworm.Framework.DbgDraw+MeshJob& job, System.Single duration, System.Boolean depthTest, UnityEngine.Rendering.CullMode cullMode, System.Boolean shaded) (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw.WireDisc (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Single radius, UnityEngine.Color color, System.Single duration, System.Boolean depthTest) (at <00000000000000000000000000000000>:0)
FastProjectile.FindNearestTransforms (UnityEngine.Vector2 center, System.Single radius, UnityEngine.LayerMask layerMask, System.Int32 numberOfNearest) (at <00000000000000000000000000000000>:0)
FastProjectile.CollidedWith (UnityEngine.Collider2D collider, UnityEngine.Vector2 hitPoint) (at <00000000000000000000000000000000>:0)
FastProjectile.Update () (at <00000000000000000000000000000000>:0)

**Comment by pschraut** [comment]
Could you please attach the entire player.log file or at least check if there was another DbgDraw error before the exception in AllocMeshJob? I suspect that the problem in AllocMeshJob might be a consequential error, possibly related to a failed initialization.

**Comment by orkuncinfer** [comment]
You are right. This is the first error im getting(this error does not occur in the editor):

Exception: ArgumentNullException: Value cannot be null.
Parameter name: shader

Oddworm.Framework.DbgDraw+DbgDrawBehaviour.CreateMaterial (System.String shaderName, UnityEngine.Rendering.CullMode cullMode, System.Boolean depthTest) (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw+DbgDrawBehaviour.CreateMaterialArray (System.String shaderName) (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw+DbgDrawBehaviour.Awake () (at <00000000000000000000000000000000>:0)
UnityEngine.GameObject.AddComponent[T] () (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw.get_instance () (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw.TryAllocMeshJob (Oddworm.Framework.DbgDraw+MeshJob& job, System.Single duration, System.Boolean depthTest, UnityEngine.Rendering.CullMode cullMode, System.Boolean shaded) (at <00000000000000000000000000000000>:0)
Oddworm.Framework.DbgDraw.WireDisc (UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Single radius, UnityEngine.Color color, System.Single duration, System.Boolean depthTest) (at <00000000000000000000000000000000>:0)
FastProjectile.FindNearestTransforms (UnityEngine.Vector2 center, System.Single radius, UnityEngine.LayerMask layerMask, System.Int32 numberOfNearest) (at <00000000000000000000000000000000>:0)
FastProjectile.CollidedWith (UnityEngine.Collider2D collider, UnityEngine.Vector2 hitPoint) (at <00000000000000000000000000000000>:0)
FastProjectile.Update () (at <00000000000000000000000000000000>:0)
UnityEngine.GameObject:AddComponent()
Oddworm.Framework.DbgDraw:get_instance()
Oddworm.Framework.DbgDraw:TryAllocMeshJob(MeshJob&, Single, Boolean, CullMode, Boolean)
Oddworm.Framework.DbgDraw:WireDisc(Vector3, Quaternion, Single, Color, Single, Boolean)
FastProjectile:FindNearestTransforms(Vector2, Single, LayerMask, Int32)
FastProjectile:CollidedWith(Collider2D, Vector2)
FastProjectile:Update()

**Comment by pschraut** [comment]
Thank you for the extra information! I've just released DbgDraw 1.2.0, which should hopefully resolve this issue. Could you please test it out and let me know if it works?

**Comment by orkuncinfer** [comment]
Thank you for your interest. The error is fixed and debugs are succesfully drawn on android.
